name: Build java application  

on:
  push:
    branches:
      - main   

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            tejasgowramma123/githubactions:latest
            tejasgowramma123/githubactions:${{github.sha}}
            tejasgowramma123/githubactions:${{github.run_number}}
